feat: zip support and Windows compatibility
tmick0/sourceknight pull request #5
Opened 2024-10-02 02:27 UTC by SparkyCloudy

2025-04-05 08:59 UTC, maxime1907 commented
any update on this @tmick0 ?

2025-04-05 19:57 UTC, tmick0 requested changes

2025-04-05 19:57 UTC, tmick0 commented on sourceknight/status.py
> +        for dep in map(dependency.from_yaml, self._ctx.defs['project']['dependencies']):
```suggestion
        for dep in map(dependency.from_yaml, self._ctx.defs['dependencies']):
```

2025-04-05 19:57 UTC, tmick0 commented on sourceknight/utils.py
Fix needed on line 156:

```py
ver = defs['sourceknight']
```

2025-04-05 19:57 UTC, tmick0 commented on sourceknight/utils.py
> +def adjust_sourcemod_platform(model):
This is a bit clunky but works for now, since the alternative would require a significant restructure of the dependency schema, and sourcemod itself is expected to be the only platform-dependent dependency in most projects.

2025-04-05 19:58 UTC, tmick0 commented
Hey, sorry about the delay, I haven't been actively maintaining this project since the main server I used sourcemod on has transitioned to CS2.

The PR in general looks good, but I ran into some issues related the the change of the context structure in my testing. I left some comments on the diff to address those.

I do not have an easy way to test on Windows so I will take your word for it that the new features work.

Thanks again for the PR!

```
$ sourceknight -p example status
No version detected in manifest, defaulting to 0.1. In the future, a version will be required in the manifest.
Traceback (most recent call last):
  File "/home/lq/repos/sourceknight_py3v/bin/sourceknight", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/lq/repos/sourceknight/sourceknight/main.py", line 40, in main
    command(ctx)(args)
  File "/home/lq/repos/sourceknight/sourceknight/status.py", line 19, in __call__
    for dep in map(dependency.from_yaml, self._ctx.defs['project']['dependencies']):
                                         ~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'project'
```

I

2025-04-06 14:19 UTC, maximee-leroyy commented
can confirm changes make the version detection work now:
```bash
(.venv) PS F:\Documents\git\github\srcdslab\sm-plugin-VIP-Core> uv pip install https://github.com/SparkyCloudy/sourceknight.git
Using Python 3.12.4 environment at: F:\Documents\git\github\srcdslab\cache\.venv
Resolved 10 packages in 1.20s
    Updated https://github.com/SparkyCloudy/sourceknight.git (e125ef4dd6d15d68e97ebe12261081b7dc97e51a)
      Built sourceknight @ git+https://github.com/SparkyCloudy/sourceknight.git@e125ef4dd6d15d68e97ebe12261081b7dc97e51aPrepared 1 package in 17.25s
Uninstalled 1 package in 47ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                                                         warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 104ms
 - sourceknight==0.4 (from git+https://github.com/SparkyCloudy/sourceknight.git@bdab37e8e9e75bc57f4cd74c37ce378924f1b5cd)
 + sourceknight==0.4 (from git+https://github.com/SparkyCloudy/sourceknight.git@e125ef4dd6d15d68e97ebe12261081b7dc97e51a)
(.venv) PS F:\Documents\git\github\srcdslab\sm-plugin-VIP-Core> sourceknight build
Updating...
Updating: sourcemod
 Downloading https://sm.alliedmods.net/smdrop/1.13/sourcemod-1.13.0-git7223-windows.zip...
Unpacking...
Unpacking sourcemod...
Unpacking archive...
Extracting .sourceknight\f850d251ae1f44599460728e413cc4ea\addons to .sourceknight\build\addons
Compiling...
Copying sources...
Building VIP_Core...
SourcePawn Compiler 1.13.0.7223
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2024 AlliedModders LLC

Code size:         145796 bytes
Data size:         24932 bytes
Stack/heap size:      17968 bytes
Total requirements:  188696 bytes
Done
(.venv) PS F:\Documents\git\github\srcdslab\sm-plugin-VIP-Core>
```

2025-04-06 18:56 UTC, tmick0 approved these changes

2025-04-06 18:56 UTC, merged

2025-04-06 18:56 UTC, tmick0 commented
Looks good. Thanks for the fix!